/// <reference path="sdl3.d.ts" />

const SDL3 = (() => require(`${__dirname}/build/Release/sdl3ts.node`))();

enum EventType {
	Quit = 0x100,
	Terminating,
	LowMemory,
	WillEnterBackground,
	DidEnterBackground,
	WillEnterForeground,
	DidEnterForeground,
	LocaleChanged,
	SystemThemeChanged,
	DisplayOrientation = 0x151,
	DisplayAdded,
	DisplayRemoved,
	DisplayMoved,
	DisplayDesktopModeChanged,
	DisplayCurrentModeChanged,
	DisplayContentScaleChanged,
	DisplayUsableBoundsChanged,
	DisplayFirst = DisplayOrientation,
	DisplayLast = DisplayUsableBoundsChanged,

	WindowShown = 0x202,
	WindowHidden,
	WindowExposed,
	WindowMoved,
	WindowResized,
	WindowPixelSizeChanged,
	WindowMetalViewResized,
	WindowMinimized,
	WindowMaximized,
	WindowRestored,
	WindowMouseEnter,
	WindowMouseLeave,
	WindowFocusGained,
	WindowFocusLost,
	WindowCloseRequested,
	WindowHitTest,
	WindowIccprofChanged,
	WindowDisplayChanged,
	WindowDisplayScaleChanged,
	WindowSafeAreaChanged,
	WindowOccluded,
	WindowEnterFullscreen,
	WindowLeaveFullscreen,
	WindowDestroyed,
	WindowHdrStateChanged,
	WindowFirst = WindowShown,
	WindowLast = WindowHdrStateChanged,

	KeyDown = 0x300,
	KeyUp,
	TextEditing,
	TextInput,
	KeymapChanged,
	KeyboardAdded,
	KeyboardRemoved,
	TextEditingCandidates,
	ScreenKeyboardShown,
	ScreenKeyboardHidden,

	MouseMotion = 0x400,
	MouseButtonDown,
	MouseButtonUp,
	MouseWheel,
	MouseAdded,
	MouseRemoved,

	JoystickAxisMotion = 0x600,
	JoystickBallMotion,
	JoystickHatMotion,
	JoystickButtonDown,
	JoystickButtonUp,
	JoystickAdded,
	JoystickRemoved,
	JoystickBatteryUpdated,
	JoystickUpdateComplete,

	GamepadAxisMotion = 0x650,
	GamepadButtonDown,
	GamepadButtonUp,
	GamepadAdded,
	GamepadRemoved,
	GamepadRemapped,
	GamepadTouchpadDown,
	GamepadTouchpadMotion,
	GamepadTouchpadUp,
	GamepadSensorUpdate,
	GamepadUpdateComplete,
	GamepadSteamHandleUpdated,

	FingerDown = 0x700,
	FingerUp,
	FingerMotion,
	FingerCanceled,

	PinchBegin = 0x710,
	PinchUpdate,
	PinchEnd,

	ClipboardUpdate = 0x900,

	DropFile = 0x1000,
	DropText,
	DropBegin,
	DropComplete,
	DropPosition,

	AudioDeviceAdded = 0x1100,
	AudioDeviceRemoved,
	AudioDeviceFormatChanged,

	SensorUpdate = 0x1200,

	PenProximityIn = 0x1300,
	PenProximityOut,
	PenDown,
	PenUp,
	PenButtonDown,
	PenButtonUp,
	PenMotion,
	PenAxis,

	CameraDeviceAdded = 0x1400,
	CameraDeviceRemoved,
	CameraDeviceApproved,
	CameraDeviceDenied,

	RenderTargetsReset = 0x2000,
	RenderDeviceReset,
	RenderDeviceLost,

	User = 0x8000,
	UserLast = 0xffff,
}

SDL3.EventType = EventType;

export default SDL3;
